import type { Feedback } from "@/lib/domain/feedback";

// Mock tickets for the Q2 launch · preflight session.
// 8 tickets, mix of statuses. createdAt is null (the domain type is
// `Timestamp | null` and we cannot construct a real Firestore Timestamp
// without importing firebase/firestore, which marketing must avoid).
// Display components must tolerate null timestamps — verify in Phase 2
// when wiring real components into demos.

const CAPTURED_URL = "https://loomly.com/pricing";
const SESSION_ID = "session_q2_launch_preflight";
const WORKSPACE_ID = "ws_northwind_studio";

const ONE_HOUR_MS = 1000 * 60 * 60;
const now = Date.now();

export const mockHeroTicket: Feedback = {
  id: "ticket_cta_overlap_iphone",
  workspaceId: WORKSPACE_ID,
  sessionId: SESSION_ID,
  title: "Get Started CTA overlaps pricing card on iPhone (<480px)",
  type: "bug",
  isResolved: false,
  createdAt: null,
  clientTimestamp: now - ONE_HOUR_MS * 2,
  commentCount: 4,
  description:
    "Get Started button on hero section appears misaligned at viewport widths below 480px, creating overlap with the pricing card component. Current button color #2E5C8A may have insufficient contrast against hero gradient background. Suggested fix: review responsive breakpoints at sm/md, validate WCAG AA contrast ratios on primary CTA against gradient backgrounds.",
  tags: ["responsive", "mobile", "hero", "pricing-page", "accessibility"],
  pageArea: "Hero / Pricing",
  url: CAPTURED_URL,
  viewportWidth: 414,
  viewportHeight: 896,
  screenshotId: null,
  screenshotStatus: "none",
  status: "open",
  assigneeId: "user_daniel",
  assigneeName: "Daniel Park",
  assigneeAvatarUrl: null,
  priority: "high",
  creatorName: "Maya Chen",
  creatorAvatarUrl: null,
  mentionedUserIds: ["user_daniel"],
};

export const mockTickets: Feedback[] = [
  mockHeroTicket,
  {
    id: "ticket_hero_gradient_safari",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Hero gradient washes brand-pink out on Safari mobile",
    type: "visual",
    isResolved: false,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 3,
    commentCount: 2,
    description:
      "On Safari iOS the hero gradient renders with reduced saturation, making the brand-pink terminal at the bottom of the gradient appear muted. Compare against Chrome iOS where saturation is correct. Likely a color-space (Display P3 vs sRGB) interpretation difference in the gradient stops.",
    tags: ["safari", "ios", "color", "hero"],
    pageArea: "Hero",
    url: CAPTURED_URL,
    viewportWidth: 390,
    viewportHeight: 844,
    screenshotId: null,
    screenshotStatus: "none",
    status: "open",
    assigneeId: "user_maya",
    assigneeName: "Maya Chen",
    assigneeAvatarUrl: null,
    priority: "medium",
    creatorName: "Maya Chen",
    creatorAvatarUrl: null,
    mentionedUserIds: [],
  },
  {
    id: "ticket_footer_link_spacing",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Footer link spacing inconsistent vs nav",
    type: "polish",
    isResolved: false,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 5,
    commentCount: 0,
    description:
      "Footer column links use 12px vertical rhythm while the top nav uses 16px. Pick one — recommend 16px throughout for legibility. Also: the rightmost footer column wraps awkwardly at md breakpoint, suggest reducing to 4 columns.",
    tags: ["typography", "spacing", "footer"],
    pageArea: "Footer",
    url: CAPTURED_URL,
    viewportWidth: 1280,
    viewportHeight: 800,
    screenshotId: null,
    screenshotStatus: "none",
    status: "open",
    assigneeId: null,
    assigneeName: null,
    assigneeAvatarUrl: null,
    priority: "low",
    creatorName: "Sarah Vance",
    creatorAvatarUrl: null,
    mentionedUserIds: [],
  },
  {
    id: "ticket_build_card_md",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Build card type feels small at md breakpoint",
    type: "visual",
    isResolved: false,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 7,
    commentCount: 3,
    description:
      "The card body copy on the 'Build with Annote' grid drops to 13px at md, which is below the brand's minimum body size of 14px. Bumping to 14px also forces the cards to grow ~6px taller — verify the grid still resolves cleanly at 3-up.",
    tags: ["typography", "responsive", "cards"],
    pageArea: "Build section",
    url: CAPTURED_URL,
    viewportWidth: 1024,
    viewportHeight: 768,
    screenshotId: null,
    screenshotStatus: "none",
    status: "open",
    assigneeId: "user_maya",
    assigneeName: "Maya Chen",
    assigneeAvatarUrl: null,
    priority: "medium",
    creatorName: "Jordan Mills",
    creatorAvatarUrl: null,
    mentionedUserIds: ["user_maya"],
  },
  {
    id: "ticket_pricing_stack_480",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Pricing card stack overlaps below 480px viewport",
    type: "bug",
    isResolved: true,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 18,
    commentCount: 5,
    description:
      "Below 480px the three pricing tiers overlapped vertically because the column gap collapsed to 0. Fixed by changing the wrap to stack at sm and forcing a 16px gap. Verified on iPhone SE viewport.",
    tags: ["responsive", "mobile", "pricing", "fixed"],
    pageArea: "Pricing",
    url: CAPTURED_URL,
    viewportWidth: 375,
    viewportHeight: 667,
    screenshotId: null,
    screenshotStatus: "none",
    status: "resolved",
    assigneeId: "user_daniel",
    assigneeName: "Daniel Park",
    assigneeAvatarUrl: null,
    priority: "medium",
    creatorName: "Maya Chen",
    creatorAvatarUrl: null,
    mentionedUserIds: [],
  },
  {
    id: "ticket_mobile_menu_jitter",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Mobile menu animation jitters on iOS Safari",
    type: "bug",
    isResolved: false,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 9,
    commentCount: 2,
    description:
      "Hamburger menu drawer slides in with visible frame drops on iOS Safari 17+. The animation uses left/right transforms — switching to transform3d(translateX) should give it GPU acceleration and smooth out the jitter.",
    tags: ["safari", "ios", "animation", "performance"],
    pageArea: "Top nav",
    url: CAPTURED_URL,
    viewportWidth: 390,
    viewportHeight: 844,
    screenshotId: null,
    screenshotStatus: "none",
    status: "open",
    assigneeId: "user_daniel",
    assigneeName: "Daniel Park",
    assigneeAvatarUrl: null,
    priority: "medium",
    creatorName: "Alex Rivera",
    creatorAvatarUrl: null,
    mentionedUserIds: ["user_daniel"],
  },
  {
    id: "ticket_testimonial_avatar_align",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Testimonial avatars misaligned in carousel",
    type: "polish",
    isResolved: true,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 30,
    commentCount: 1,
    description:
      "Avatar bubbles in the testimonial carousel were vertically center-aligned, which felt visually off because the testimonial text is left-aligned and long-form. Switched to align-items: flex-start. Verified at all breakpoints.",
    tags: ["typography", "carousel", "fixed"],
    pageArea: "Testimonials",
    url: CAPTURED_URL,
    viewportWidth: 1280,
    viewportHeight: 800,
    screenshotId: null,
    screenshotStatus: "none",
    status: "resolved",
    assigneeId: "user_alex",
    assigneeName: "Alex Rivera",
    assigneeAvatarUrl: null,
    priority: "low",
    creatorName: "Sarah Vance",
    creatorAvatarUrl: null,
    mentionedUserIds: [],
  },
  {
    id: "ticket_logo_crop_tablet",
    workspaceId: WORKSPACE_ID,
    sessionId: SESSION_ID,
    title: "Logo wordmark crops on tablet portrait",
    type: "bug",
    isResolved: false,
    createdAt: null,
    clientTimestamp: now - ONE_HOUR_MS * 11,
    commentCount: 1,
    description:
      "On iPad portrait the Loomly wordmark in the top nav clips on the right edge because the logo container has a fixed width that doesn't account for the longer brand mark. Either shrink the wordmark below md, or make the container width fluid.",
    tags: ["responsive", "tablet", "nav", "logo"],
    pageArea: "Top nav",
    url: CAPTURED_URL,
    viewportWidth: 768,
    viewportHeight: 1024,
    screenshotId: null,
    screenshotStatus: "none",
    status: "open",
    assigneeId: "user_maya",
    assigneeName: "Maya Chen",
    assigneeAvatarUrl: null,
    priority: "low",
    creatorName: "Jordan Mills",
    creatorAvatarUrl: null,
    mentionedUserIds: ["user_maya"],
  },
];

export const mockOpenTickets = mockTickets.filter((t) => !t.isResolved);
export const mockResolvedTickets = mockTickets.filter((t) => t.isResolved);
